export const cities: { [key: string]: string[] } = {
    ET: ['Addis Ababa', 'Adama', 'Bahar dar'],
    US: ['New York City', 'Los Angeles', 'Chicago'],
    GB: ['London', 'Manchester', 'Edinburgh'],
    FR: ['Paris', 'Marseille', 'Lyon'],
    DE: ['Berlin', 'Munich', 'Hamburg'],
    IN: ['Mumbai', 'Delhi', 'Bangalore'],
    JP: ['Tokyo', 'Osaka', 'Kyoto'],
    AU: ['Sydney', 'Melbourne', 'Brisbane'],
    CA: ['Toronto', 'Vancouver', 'Montreal'],
    BR: ['Sao Paulo', 'Rio de Janeiro', 'Brasilia'],
    RU: ['Moscow', 'Saint Petersburg', 'Novosibirsk'],
    CN: ['Beijing', 'Shanghai', 'Guangzhou'],
    IT: ['Rome', 'Milan', 'Venice'],
    ES: ['Madrid', 'Barcelona', 'Valencia'],
    MX: ['Mexico City', 'Cancun', 'Guadalajara'],
    AR: ['Buenos Aires', 'Cordoba', 'Rosario'],
    ZA: ['Johannesburg', 'Cape Town', 'Durban'],
    EG: ['Cairo', 'Alexandria', 'Giza'],
    NG: ['Lagos', 'Abuja', 'Kano'],
    SA: ['Riyadh', 'Jeddah', 'Mecca'],
    ID: ['Jakarta', 'Surabaya', 'Bandung'],
    TR: ['Istanbul', 'Ankara', 'Izmir'],
    PL: ['Warsaw', 'Krakow', 'Gdansk'],
    PK: ['Karachi', 'Lahore', 'Islamabad'],
    KR: ['Seoul', 'Busan', 'Incheon'],
    IR: ['Tehran', 'Mashhad', 'Isfahan'],
    DZ: ['Algiers', 'Oran', 'Constantine'],
    CO: ['Bogota', 'Medellin', 'Cali'],
    KE: ['Nairobi', 'Mombasa', 'Kisumu'],
    PE: ['Lima', 'Arequipa', 'Cusco'],
    VE: ['Caracas', 'Maracaibo', 'Valencia'],
    SE: ['Stockholm', 'Gothenburg', 'Malmo'],
    CH: ['Zurich', 'Geneva', 'Basel'],
    NL: ['Amsterdam', 'Rotterdam', 'The Hague'],
    NO: ['Oslo', 'Bergen', 'Trondheim'],
    FI: ['Helsinki', 'Tampere', 'Turku'],
    AT: ['Vienna', 'Salzburg', 'Graz'],
    BE: ['Brussels', 'Antwerp', 'Ghent'],
    PT: ['Lisbon', 'Porto', 'Faro'],
    GR: ['Athens', 'Thessaloniki', 'Heraklion'],
    CZ: ['Prague', 'Brno', 'Ostrava'],
    HU: ['Budapest', 'Debrecen', 'Szeged'],
    RO: ['Bucharest', 'Cluj-Napoca', 'Timisoara'],
    DK: ['Copenhagen', 'Aarhus', 'Odense'],
    IE: ['Dublin', 'Cork', 'Galway'],
    MY: ['Kuala Lumpur', 'Penang', 'Johor Bahru'],
    SG: ['Singapore', 'Jurong', 'Woodlands'],
    TH: ['Bangkok', 'Phuket', 'Chiang Mai'],
    PH: ['Manila', 'Cebu City', 'Davao City'],
    IL: ['Jerusalem', 'Tel Aviv', 'Haifa'],
    UA: ['Kyiv', 'Kharkiv', 'Lviv'],
    MA: ['Casablanca', 'Rabat', 'Marrakesh'],
    GH: ['Accra', 'Kumasi', 'Tamale'],
    CI: ['Abidjan', 'Yamoussoukro', 'Bouake'],
    UG: ['Kampala', 'Entebbe', 'Gulu'],
    GW: ['Bissau', 'Bafata', 'Gabu'],
    MR: ['Nouakchott', 'Nouadhibou', 'Rosso'],
    TN: ['Tunis', 'Sfax', 'Gabes'],
    LY: ['Tripoli', 'Benghazi', 'Misrata'],
    TZ: ['Dar es Salaam', 'Zanzibar City', 'Arusha'],
    RW: ['Kigali', 'Butare', 'Gisenyi'],
    CD: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi'],
    ZM: ['Lusaka', 'Ndola', 'Kitwe'],
    SN: ['Dakar', 'Thies', 'Saint-Louis'],
    SD: ['Khartoum', 'Omdurman', 'Port Sudan'],
    SS: ['Juba', 'Wau', 'Malakal'],
    AO: ['Luanda', 'NDalatando', 'Lobito'],
    ZW: ['Harare', 'Bulawayo', 'Chitungwiza'],
    BW: ['Gaborone', 'Francistown', 'Molepolole'],
    NA: ['Windhoek', 'Rundu', 'Walvis Bay'],
    LS: ['Maseru', 'Teyateyaneng', 'Mafeteng'],
    SZ: ['Mbabane', 'Manzini', 'Big Bend'],
    MU: ['Port Louis', 'Beau Bassin', 'Vacoas'],
    SC: ['Victoria', 'Anse Boileau', 'Bel Air'],
    MG: ['Antananarivo', 'Toamasina', 'Antsirabe'],
    MZ: ['Maputo', 'Matola', 'Beira'],
    MW: ['Lilongwe', 'Blantyre', 'Mzuzu'],
  CM: ['Douala', 'Yaounde', 'Bamenda'],
  NE: ['Niamey', 'Zinder', 'Maradi'],
  TG: ['Lome', 'Kara', 'Sokode'],
  BJ: ['Porto-Novo', 'Cotonou', 'Parakou'],
  LR: ['Monrovia', 'Gbarnga', 'Buchanan'],
  SL: ['Freetown', 'Bo', 'Kenema'],
  GN: ['Conakry', 'Nzerekore', 'Kindia'],
  GM: ['Banjul', 'Serekunda', 'Brikama'],
  CV: ['Praia', 'Mindelo', 'Santa Maria'],
}